/* volunteer type */
export const VOLUNTEER_GET_REQUEST = "VOLUNTEER_REGISTER_REQUEST";
export const VOLUNTEER_GET_SUCCESS = "VOLUNTEER_CREATE_SUCCESS";
export const VOLUNTEER_FAIL = "VOLUNTEER_FAIL";

/* become a volunteer */
export const BECOME_CREATE_REQUEST  = "BECOME_CREATE_REQUEST";
export const BECOME_CREATE_SUCCESS = "BECOME_CREATE_SUCCESS";
export const BECOME_FAIL = "BECOME_FAIL";

/* slider */
export const SLIDER_GET_REQUEST  = "SLIDER_GET_REQUEST";
export const SLIDER_GET_SUCCESS = "SLIDER_GET_SUCCESS";
export const SLIDER_GET_FAIL = "SLIDER_GET_FAIL";

/* slider */
export const CONTACT_CREATE_REQUEST  = "CONTACT_CREATE_REQUEST";
export const CONTACT_CREATE_SUCCESS = "CONTACT_CREATE_SUCCESS";
export const CONTACT_CREATE_FAIL = "CONTACT_CREATE_FAIL";

/* blog */
export const BLOG_GET_REQUEST  = "BLOG_GET_REQUEST";
export const BLOG_GET_SUCCESS = "BLOG_GET_SUCCESS";
export const BLOG_GET_FAIL = "BLOG_GET_FAIL";

/* gallary */
export const GET_GALLARY_REQUEST = "GET_GALLARY_REQUEST";
export const GET_GALLARY_SUCCESS = "GET_GALLARY_SUCCESS";
export const GET_GALLARY_FAIL = "GET_GALLARY_FAIL";

/* make donation */
export const CREATE_MAKE_DONATION_REQUEST = "CREATE_MAKE_DONATION_REQUEST";
export const CREATE_MAKE_DONATION_SUCCESS = "CREATE_MAKE_DONATION_SUCCESS";
export const CREATE_MAKE_DONATION_FAIL = "CREATE_MAKE_DONATION_FAIL";  

/* registor the form * */
export const CREATE_REGISTRATION_REQUEST = "CREATE_REGISTRATION_REQUEST";
export const CREATE_REGISTRATION_SUCCESS = "CREATE_REGISTRATION_SUCCESS";
export const CREATE_REGISTRATION_FAIL = "CREATE_REGISTRATION_FAIL";
